### PR TITLE
add login using pair phone functionality

### PR DESCRIPTION
**Pull request by aryo-sr**
Need the latest whatsmeow version, or at least after july 2023.

References: 
+ https://pkg.go.dev/go.mau.fi/whatsmeow#Client.PairPhone
+ https://faq.whatsapp.com/1324084875126592

### CODE REVIEW

**Comment by dimaskiddo** [comment]
I'am sorry just see this and this is looks good and cool. I'll try to read this first. Thank you so much 😄

**Comment by ibnux** [comment]
It is working?

It will really helpfull when the WhatsApp for gateway is in home 

I just need to remote it with TeamViewer and add the number 😁

**Comment by aryo-sr** [comment]
> It is working?
> 
> It will really helpfull when the WhatsApp for gateway is in home
> 
> I just need to remote it with TeamViewer and add the number 😁

@ibnux , I have the wa number used inside genymotion, personal use license, so it has no camera. That's the main motivation to implement this.

**Comment by ibnux** [comment]
Ah yes
The first time I use the gateway, is using genymotion too, but the camera is working, and it's hard to align webcam with QRcode in my phone 😁

Then I buy old android phone Samsung J1 as dedicated WhatsApp and SMS gateway

**Comment by ibnux** [comment]
@aryo-sr saya coba, dapat error `Error Connect WhatsApp Client Datastore`

**Comment by aryo-sr** [comment]
@ibnux I see, apparently the latest whatsmeow env variable for sqlite datastore URI needs to be changed.

Original value:
```
WHATSAPP_DATASTORE_URI=file:WhatsApp.db?_foreign-keys=on
```

Change to:
```
WHATSAPP_DATASTORE_URI=file:WhatsApp.db?_pragma=foreign-keys(1)
```

For reference: https://github.com/tulir/whatsmeow/issues/454

**Comment by dimaskiddo** [comment]
Merged and Released in [v1.6.0](https://github.com/dimaskiddo/go-whatsapp-multidevice-rest/releases/tag/v1.6.0) Cheers 🥂 
Btw sorry for my bad merge commit name @aryo-sr but i still do want to put your name as contributors so i edit the changelog yeaah... 🤘

**Comment by ibnux** [comment]
@aryo-sr @dimaskiddo 
i can't seem to make it work
always getting error `info query returned status 400: bad-request`

i read on this https://pkg.go.dev/go.mau.fi/whatsmeow#Client.PairPhone
`The clientType parameter must be one of the PairClient* constants, but which one doesn't matter. The client display name must be formatted as `Browser (OS)`, and only common browsers/OSes are allowed (the server will validate it and return 400 if it's wrong). `

i change the WHATSAPP_USER_AGENT_NAME to `Mac OS` still error 400
any other parameter need to send to login/pair?

go version go1.21.3 linux/amd64

**Comment by aryo-sr** [comment]
@ibnux I believe the WHATSAPP_USER_AGENT_NAME should follow the format "**Chrome (`Mac OS`)**", like the one issue at https://github.com/tulir/whatsmeow/issues/449.

**Comment by ibnux** [comment]
thanks, yes it need to change to that format

i was think it just `Mac OS` because when scanned it will show `Chrome (Mac OS)` at WhatsApp

updating the wiki

https://github.com/dimaskiddo/go-whatsapp-multidevice-rest/wiki/Endpoint#loginpair

**Pull request merged**
